feature : TX 2412 upgrade (TX EDC 0.8.0 release)
eclipse-tractusx/knowledge-agents-edc pull request #261
Opened 2024-11-22 11:41 UTC by drcgjung

## WHAT

Adapts dependencies and base images to the TX EDC 0.8.0 release. 

## WHY

Provide the most possible compatibility of the agent planes.

## FURTHER NOTES

Closes #35 # <-- _insert Issue number if one exists_

2024-11-22 11:43 UTC, drcgjung commented
there is a "restricted" dependency 
maven/mavencentral/org.flywaydb/flyway-database-postgresql/10.21.0, , restricted, clearlydefined
which comes through TX EDC ... an IP check should already been issued at eclipse, I would guess.

2024-11-25 09:23 UTC, almadigabor requested changes
Just one minor request.

2024-11-25 09:23 UTC, almadigabor commented on DEPENDENCIES
Please update the DEPENDENCIES file before I merge the PR. There should be no restricted libraries once you run the dash tool.

2024-11-25 10:49 UTC, drcgjung commented on DEPENDENCIES
There are clear rules for commiters and there are the obvious exceptions

https://github.com/eclipse-tractusx/tractusx-edc/blob/25da0bc59107d8bc379d8162002698165ecefff9/DEPENDENCIES#L571

So If you could please open an IP check on that one line

maven/mavencentral/org.flywaydb/flyway-database-postgresql/10.21.0, , restricted, clearlydefined

2024-11-26 12:32 UTC, almadigabor commented on DEPENDENCIES
I know the process, might have been on a different branch when I ran the command. Now the IP ticket is created, let's wait for approval then the DEPENDENCIES file can be updated.

Output:
```
A review is required for maven/mavencentral/org.flywaydb/flyway-database-postgresql/10.21.0.
A review request was created https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/17433 .
```

2024-12-02 08:50 UTC, merged