fix: #46 do not use build-args in the dockerfiles, else we risk corrupt images
eclipse-tractusx/knowledge-agents-edc pull request #48
Opened 2023-09-08 08:19 UTC by drcgjung

## WHAT

Backport of solution to #46 

## WHY

seee #46 

## FURTHER NOTES

Closes #46

2023-09-13 13:55 UTC, carslen requested changes
Same issues as in #47, please do not manage forks in upstream workflows.

2023-09-14 06:00 UTC, drcgjung commented
> Same issues as in #47, please do not manage forks in upstream workflows.

I removed all catenax-ng fork references.

2023-09-14 15:53 UTC, the-tatanka approved these changes

2023-09-18 11:24 UTC, carslen approved these changes
LGTM

There are still if clauses which might use ghcr.io as container registry, which is unwanted, but for now I'll accept this.

2023-09-18 11:24 UTC, merged